version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      #dockerfile: DockerfileKirti
    ports:
      - "3000:5173"
      #- "3000:3000"

    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: PCS
      DB_PASSWORD: pa2024
      DB_NAME: pcs

  db:
    image: ninerem/pcs:latest
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcs
      MYSQL_USER: PCS
      MYSQL_PASSWORD: pa2024
    volumes:
      - db-data:/var/lib/mysql
      #- ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pcs-phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy 

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
