version: '3.8'

services:
  frontend:
  image: ninerem/docker-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      #dockerfile: DockerfileKirti
    ports:
      - "3000:5173"
      #- "3000:3000"

    networks:
      - pcs-network

  backend:
    image: ninerem/docker-backend:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - pcs-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: PCS
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: pcs
    secrets:
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: pcs
      MYSQL_USER: PCS
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

  db:
    image: ninerem/pcs-sql:latest
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcs
      MYSQL_USER: PCS
      MYSQL_PASSWORD: pa2024
    volumes:
      - db-data:/var/lib/mysql
      #- ./database:/docker-entrypoint-initdb.d
    networks:
      - pcs-network


networks:
  pcs-network:
    driver: bridge
volumes:
  db-data:

secrets:
  db_root_password:
    file: ./db_root_password.secret
  db_password:
    file: ./db_password.secret

